### ISSUE TITLE
Incompatible with Bitbucket under default configuration

### ISSUE THREAD

**Issue by ChristopherMWood** [dansiegel/Mobile.BuildTools#136]
# Description

I have a mobile project being hosted on Bitbucket and if I add either the latest stable release of mobile build tools or the current pre release version to the project, it fails to build when I run a pipeline to run Unit tests. Below is the following errors when running under the pre release version for 2.0. AppCenter and local builds work as expected.

```
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018: The "LocateBuildToolsConfigTask" task failed unexpectedly. [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621 [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018: File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:    at Mobile.BuildTools.Utils.ConfigHelper.GetConfig(String path) [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:    at Mobile.BuildTools.Tasks.LocateBuildToolsConfigTask.Execute() in d:\a\1\s\src\Mobile.BuildTools\Tasks\LocateBuildToolsConfigTask.cs:line 70 [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:  [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
/root/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/Mobile.BuildTools.targets(35,5): error MSB4018:  [/opt/atlassian/pipelines/agent/build/UHS/UHS.csproj]
```

Here is my bitbucket-pipelines.yml file that runs the pipeline
```
# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        name: Run Unit Tests
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - dotnet test UHS.UnitTests /p:CollectCoverage=true
```

It seems that the project cannot correctly open or use the json file. This same error occurs in the current stable version but instead fails when trying to locate and use the secrets.json file it's expecting.

I am able to build locally and on AppCenter without any issues so this is purely a Bitbucket incompatibility it seems.

## Reproduction Steps

1. Make a pipeline on Bitbucket to build a project with Mobile.Buildtools as a dependency
2. Run pipeline

## Expected Behavior

I would expect it to be able to load the json files without issue under default settings.

## Actual Behavior

Cannot build a single pipeline after adding Nuget package for any version.

## Environment

- Tools: Bitbucket pipelines
- BuildTools Version: [1.4.0.638] & [2.0.0.1007-pre]
- Build Target Framework: [netstandard2.0|Xamarin.iOS|Xamarin.Android]

## Reproduction App

The app I am working on is in bitbucket under a private repository so I cannot share it here, but the project I'm working on is a vanilla Xamarin Forms cross platform project.
