### ISSUE TITLE
AzureDevOps build "No value was provided for the Manifest"

### ISSUE THREAD

**Issue by Seuleuzeuh** [dansiegel/Mobile.BuildTools#281]
# Description

Hi @dansiegel, first of it, thanks for this awsome package 😸.
I've a Xamarin.Forms App with an Android platform. I've implemented BuildTools on it, works perfectly on local machine (Windows & MacOS).
But failed in an AzureDevOps pipeline.

Problems raised by the msbuild (full build log is attached) : 

> /Users/runner/.nuget/packages/mobile.buildtools/2.0.245/build/AndroidManifest.targets(28,5): warning : No value was provided for the Manifest. Unable to process Manifest Tokens 

And

> /Users/runner/.nuget/packages/mobile.buildtools/2.0.245/build/AndroidManifest.targets(48,5): error MSB4044: The "AutomaticBuildVersioningTask" task was not given a value for the required parameter "ManifestPath". 

## Reproduction Steps

Don't know 

## Expected Behavior

Build in AZDevOps like in local machine

## Actual Behavior

Build failed whith `error MSB4044: The "AutomaticBuildVersioningTask" task was not given a value for the required parameter "ManifestPath"`

## Environment

- OS: OSX
- IDE: CLI
- BuildTools Version: 2.0.245
- IDE Version: 
- Build Target Framework: Xamarin.Android

## Reproduction App

Part of my Yaml pipeline description :  
```yaml
 - task: NuGetAuthenticate@0

 - task: XamarinAndroid@1
   inputs:
     projectFile: '**/*Droid*.csproj'
     outputDirectory: '$(outputDirectory)'
     configuration: '$(buildConfiguration)'
     msbuildVersionOption: 'latest'
     msbuildArguments: ' /r /verbosity:diag /t:SignAndroidPackage /p:AndroidKeyStore="True" /p:AndroidSigningKeyStore="$(keystore.secureFilePath)" /p:AndroidSigningKeyPass="$(keystorePassword)" /p:AndroidSigningKeyAlias="$(keystoreAlias)" /p:AndroidSigningStorePass="$(keystorePassword)"'
```
     
I can share the full Yaml file if needed.

[BuildLog.zip](https://github.com/dansiegel/Mobile.BuildTools/files/6863348/BuildLog.zip)

**Comment by dansiegel** [comment]
It's really hard for me to make any determination here without having a binlog. If you can update the build step's `msbuildArguments` to include `/bl` and then publish the binlog on pipeline failure.

```yaml
- task: NuGetAuthenticate@0

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    msbuildArguments: ' /r /bl /t:SignAndroidPackage /p:AndroidKeyStore="True" /p:AndroidSigningKeyStore="$(keystore.secureFilePath)" /p:AndroidSigningKeyPass="$(keystorePassword)" /p:AndroidSigningKeyAlias="$(keystoreAlias)" /p:AndroidSigningStorePass="$(keystorePassword)"'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Binlog'
  condition: failed()
  inputs:
    artifactName: binlog
    targetPath: 'msbuild.binlog'

```
